from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """
    Validation schema for standard text Q&A support queries.
    """
    prompt: str = Field(..., example="What parameters are required for POST /checkout?")
    top_k: Optional[int] = Field(default=3, ge=1, le=20, description="Number of similarity chunks to retrieve")


class SourceCitation(BaseModel):
    """
    Schema representing a reference document segment cited by the model.
    """
    document_id: str = Field(..., description="UUID representing the master document")
    filename: str = Field(..., description="Name of the cited document file")
    similarity_score: float = Field(..., description="Cosine similarity score calculated via pgvector")
    api_path: Optional[str] = Field(default=None, description="API path if parsed from OpenAPI/Postman specs")
    http_method: Optional[str] = Field(default=None, description="HTTP method if parsed from specs")
    page_number: Optional[int] = Field(default=None, description="Page number if parsed from PDF manual")
    section: Optional[str] = Field(default=None, description="Section heading title if parsed from Word manual")


class ChatResponse(BaseModel):
    """
    Schema containing synthesized answers and document citations.
    """
    query: str = Field(..., description="The user's original query prompt")
    answer: str = Field(..., description="Grounded response generated by the local LLM")
    sources: List[SourceCitation] = Field(default_factory=list, description="Reference list of source documents cited")
    metrics: Dict[str, Any] = Field(default_factory=dict, description="Performance latency timings in seconds")


class VisionChatResponse(ChatResponse):
    """
    Extended schema for image troubleshooting responses, including OCR text and visual details.
    """
    extracted_text: str = Field(..., description="Literal code/text extracted from screenshot via OCR")
    vision_description: str = Field(..., description="Visual scene classification and layout parsing description")


class IngestionResponse(BaseModel):
    """
    Schema returning document ingestion execution statistics.
    """
    status: str = Field(..., example="success", description="Status code ('success', 'skipped')")
    document_id: Optional[str] = Field(default=None, description="Registered UUID of the document")
    filename: str = Field(..., description="Name of the processed file")
    file_type: str = Field(..., description="Detected format category (openapi, postman, pdf, docx, txt)")
    total_chunks: int = Field(..., description="Number of text chunks embedded and saved in pgvector")
    duration_seconds: float = Field(..., description="Ingestion processing time in seconds")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Extracted global document metadata properties")


class HealthResponse(BaseModel):
    """
    Schema reflecting application health diagnostics.
    """
    status: str = Field(default="ok", example="ok")
    database_connected: bool = Field(..., description="PostgreSQL pgvector connectivity status")
    ollama_reachable: bool = Field(..., description="Ollama API connection status")
    timestamp: str = Field(..., description="Backend local system ISO timestamp")
